using System;
using System.IO;
using System.Text;

namespace CSharp_EmbedBytes
{
    class Program
    {
        private const string SCAN_FOLDER = @"..\..\Animations";
        private const string OUTPUT_FILE = @"..\..\Output.cs";
        static void Main(string[] args)
        {
            using (FileStream output = File.Open(OUTPUT_FILE, FileMode.OpenOrCreate, FileAccess.Write, FileShare.ReadWrite))
            {
                using (StreamWriter sw = new StreamWriter(output))
                {
                    sw.WriteLine(@"using System;");
                    sw.WriteLine(@"class AutogeneratedCode");
                    sw.WriteLine("{0}", @"{");

                    sw.WriteLine("\t#region Autogenerated embedded variables");
                    sw.WriteLine();

                    StringBuilder sb = new StringBuilder();

                    DirectoryInfo di = new DirectoryInfo(SCAN_FOLDER);
                    foreach (FileInfo fi in di.GetFiles())
                    {
                        Console.WriteLine("Embed file: {0}", fi.Name);
                        using (FileStream fs = File.Open(fi.FullName, FileMode.Open, FileAccess.Read, FileShare.Read))
                        {
                            byte[] buffer = new byte[(int)fs.Length];
                            fs.Read(buffer, 0, buffer.Length);

                            if (sb.Length > 0)
                            {
                                sb.Remove(0, sb.Length);
                            }
                            sb.AppendFormat("public static readonly byte[] EMBED_{0} = ", Path.GetFileNameWithoutExtension(fi.Name).Replace(".", string.Empty).ToUpper());

                            sb.Append(@"{");

                            for (int b = 0; b < buffer.Length; ++b)
                            {
                                if ((b + 1) == buffer.Length)
                                {
                                    sb.Append(buffer[b]);
                                }
                                else
                                {
                                    sb.AppendFormat("{0},", buffer[b]);
                                }
                            }

                            sb.AppendLine(@"};");

                            sw.WriteLine("\t{0}", sb.ToString());
                        }
                    }

                    sw.WriteLine();

                    sw.WriteLine("\t#endregion Autogenerated embedded variables");

                    sw.WriteLine("{0}", @"}");

                }
            }
        }
    }
}
